LOAD synthetic_mutating;
ATTACH ':memory:' AS kv (TYPE synthetic_mutating);
CREATE TABLE kv.kv_store(key TEXT, value TEXT);
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 0 THEN 1 ELSE 0 END;
INSERT INTO kv.kv_store(key, value) VALUES('alpha', 'first');
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 1 THEN 1 ELSE 0 END;
SELECT CASE WHEN (SELECT value FROM kv.kv_store WHERE key = 'alpha') = 'first' THEN 1 ELSE 0 END;
INSERT INTO kv.kv_store(key, value) VALUES('beta', 'second');
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 2 THEN 1 ELSE 0 END;
SELECT CASE WHEN (SELECT value FROM kv.kv_store WHERE key = 'beta') = 'second' THEN 1 ELSE 0 END;
BEGIN;
INSERT INTO kv.kv_store(key, value) VALUES('gamma', 'third');
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 3 THEN 1 ELSE 0 END;
SELECT CASE WHEN (SELECT value FROM kv.kv_store WHERE key = 'gamma') = 'third' THEN 1 ELSE 0 END;
COMMIT;
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 3 THEN 1 ELSE 0 END;
SELECT CASE WHEN (SELECT value FROM kv.kv_store WHERE key = 'gamma') = 'third' THEN 1 ELSE 0 END;
BEGIN;
INSERT INTO kv.kv_store(key, value) VALUES('delta', 'fourth');
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 4 THEN 1 ELSE 0 END;
ROLLBACK;
SELECT CASE WHEN (SELECT count(value) FROM kv.kv_store) = 3 THEN 1 ELSE 0 END;
SELECT CASE WHEN NOT EXISTS (SELECT value FROM kv.kv_store WHERE key = 'delta') THEN 1 ELSE 0 END;
